name: 本地构建 (Docker Hub + GHCR)

on:
  workflow_dispatch:
    inputs:
      version:
        description: '要构建的版本号 (例如: 1.9.0) '
        required: false
        default: 'v1.9.0'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write    # 用于推送到 GHCR
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 登录 GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 构建并推送到 Docker Hub 和 GHCR（多标签）
      - name: Build and Push Docker Images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.local
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ldxw/toolbox:latest
            ldxw/toolbox:${{ github.event.inputs.version }}
            ghcr.io/${{ github.repository_owner }}/toolbox:latest
            ghcr.io/${{ github.repository_owner }}/toolbox:${{ github.event.inputs.version }}
